#!/bin/bash

# I want to make sure that the directory is clean and has nothing left over from
# previous deployments. The servers auto scale so the directory may or may not
# exist.

#yum intall -y nginx
#rm -f /usr/share/nginx/html/index.html

if [ -d /var/www/html ]; then
    rm -rf /var/www/html
fi
mkdir -vp /var/www/html


if [ -d /var/www/html/antarinbarang.com ]; then
    rm -rf /var/www/html/antarinbarang.com
fi
mkdir -vp /var/www/html/antarinbarang.com